server:
  port: 18082
spring:
  application:
    name: sentinel-feign-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080