server:
  port: 18083
spring:
  application:
    name: sentinel-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      scg:
        fallback:
          response-status: 426
          mode: response
          response-body: error request
    gateway:
      routes:
        - id: test_route
          uri: lb://sentinel-gateway-service
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1  #这里的作用是拦截请求后转发的地址去掉一个断言的前缀

